server:
  port: 18090

spring:
  application:
    name: commodity-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 3
