server:
  port: 18080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/